# Generated by Django 4.0.3 on 2022-03-30 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Barbero',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_apellido', models.CharField(max_length=60)),
                ('dni', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_apellido', models.CharField(max_length=60)),
                ('telefono', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.IntegerField()),
                ('horario', models.IntegerField()),
            ],
        ),
    ]
