# Generated by Django 4.0.3 on 2022-03-31 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appbarberia', '0002_remove_turno_horario'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='horario',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
