# Generated by Django 4.0.3 on 2022-03-31 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appbarberia', '0003_turno_horario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='barbero',
            old_name='nombre_apellido',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='nombre_apellido',
            new_name='nombre',
        ),
    ]
